version: "3.3"
services:
  test_db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$TEST_DATABASE_NAME

  test_backend:
    depends_on:
      - test_db
    command: ['bash', 'scripts/test.sh']
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=test_db
    build:
      args:
        - INSTALL_DEV=true
      context: .
      dockerfile: Dockerfile



