"""'init-db'

Revision ID: 24a84265df8a
Revises: 
Create Date: 2023-02-02 12:14:01.456313

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "24a84265df8a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customer_id"), "customer", ["id"], unique=False)
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employee_email"), "employee", ["email"], unique=True)
    op.create_index(op.f("ix_employee_id"), "employee", ["id"], unique=False)
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "balance",
            sa.Numeric(precision=10, scale=2),
            server_default="0.00",
            nullable=True,
        ),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_id"), "account", ["id"], unique=False)
    op.create_table(
        "history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("from_account_id", sa.Integer(), nullable=False),
        sa.Column("to_account_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_history_id"), "history", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_history_id"), table_name="history")
    op.drop_table("history")
    op.drop_index(op.f("ix_account_id"), table_name="account")
    op.drop_table("account")
    op.drop_index(op.f("ix_employee_id"), table_name="employee")
    op.drop_index(op.f("ix_employee_email"), table_name="employee")
    op.drop_table("employee")
    op.drop_index(op.f("ix_customer_id"), table_name="customer")
    op.drop_table("customer")
    # ### end Alembic commands ###
